stages:
  - test
  - build
  - deploy
  - post_deploy
  - smoke_test
  - changelog
  - wiki_update

variables:
  IMAGE_NAME: 192.168.1.66:5050/monarch/fastapi-todo-devops

test:
  stage: test
  image: python:3.11-slim
  tags:
    - runner
  services:
    - name: postgres:16-alpine
      alias: postgres
  variables:
    POSTGRES_DB: todo_db
    POSTGRES_USER: todo_user
    POSTGRES_PASSWORD: change_me_dev_only
    POSTGRES_PORT: "5432"
  script:
    - pip install --no-cache-dir -r requirements.txt
    - export DATABASE_URL="postgresql+psycopg://todo_user:change_me_dev_only@postgres:5432/todo_db"
    - export PYTHONPATH="$CI_PROJECT_DIR"
    - |
      python - <<'PY'
      import os
      import time
      import psycopg

      for i in range(30):
          try:
              with psycopg.connect(
                  host="postgres",
                  dbname=os.environ["POSTGRES_DB"],
                  user=os.environ["POSTGRES_USER"],
                  password=os.environ["POSTGRES_PASSWORD"],
                  port=os.environ["POSTGRES_PORT"],
              ):
                  print("Postgres is ready")
                  break
          except Exception as e:
              print(f"Waiting for Postgres... {i+1}/30: {e}")
              time.sleep(2)
      else:
          raise SystemExit("Postgres did not become ready in time")
      PY
    - alembic upgrade head
    - pytest -v

build:
  stage: build
  image: docker:27
  tags:
    - runner
  services:
    - name: docker:27-dind
      command: ["--insecure-registry=192.168.1.66:5050"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login 192.168.1.66:5050 -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker version
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  tags:
    - deploy-shell
  only:
    - main
  script:
    - |
      cat > .env <<EOF
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_PORT=${POSTGRES_PORT}
      DATABASE_URL=${DATABASE_URL}
      EOF
    - chmod +x deploy.sh
    - ./deploy.sh

post_deploy:
  stage: post_deploy
  tags:
    - deploy-shell
  only:
    - main
  script:
    - curl -f http://127.0.0.1:8080/health

smoke_test:
  stage: smoke_test
  tags:
    - deploy-shell
  only:
    - main
  script:
    - chmod +x scripts/smoke_test.sh
    - APP_URL="http://127.0.0.1:8080" EXPECTED_COMMIT_SHA="$CI_COMMIT_SHORT_SHA" ./scripts/smoke_test.sh

changelog:
  stage: changelog
  image: alpine:3.20
  tags:
    - runner
  only:
    - main
  before_script:
    - apk add --no-cache bash git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.local"
    - chmod +x update_changelog.sh
  script:
    - ./update_changelog.sh
    - |
      if git diff --quiet CHANGELOG.md; then
        echo "CHANGELOG.md не изменился"
        exit 0
      fi
    - git add CHANGELOG.md
    - 'git commit -m "ci: update changelog [skip ci]"'
    - 'git remote set-url origin "http://oauth2:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"'
    - 'git push origin HEAD:${CI_COMMIT_BRANCH}'

wiki_update:
  stage: wiki_update
  image: alpine:3.20
  tags:
    - runner
  only:
    - main
  before_script:
    - apk add --no-cache curl
  script:
    - |
      WIKI_CONTENT="# FastAPI Todo DevOps

      ## О проекте
      ВКР DevOps-проект: FastAPI + Docker + GitLab CI/CD + Docker Compose.

      ## Что уже реализовано
      - test
      - build
      - deploy
      - post_deploy
      - автоматическая публикация CHANGELOG

      ## Проверка приложения
      Health endpoint:
      - /health
      "
      STATUS_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
        --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/wikis/home")

      if [ "$STATUS_CODE" = "200" ]; then
        curl --request PUT \
          --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
          --data-urlencode "title=Home" \
          --data-urlencode "content=${WIKI_CONTENT}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/wikis/home"
      else
        curl --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
          --data-urlencode "title=Home" \
          --data-urlencode "content=${WIKI_CONTENT}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/wikis"
      fi