stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: 192.168.1.66:5050/monarch/fastapi-todo-devops

test:
  stage: test
  image: python:3.11-slim
  tags:
    - runner
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pytest

build:
  stage: build
  image: docker:27
  tags:
    - runner
  services:
    - name: docker:27-dind
      command: ["--insecure-registry=192.168.1.66:5050"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login 192.168.1.66:5050 -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker version
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  tags:
    - deploy-shell
  only:
    - main
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
