stages:
  - test
  - build
  - deploy
  - post_deploy
  - changelog
  - wiki_update

variables:
  IMAGE_NAME: 192.168.1.66:5050/monarch/fastapi-todo-devops

test:
  stage: test
  image: python:3.11-slim
  tags:
    - runner
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pytest

build:
  stage: build
  image: docker:27
  tags:
    - runner
  services:
    - name: docker:27-dind
      command: ["--insecure-registry=192.168.1.66:5050"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login 192.168.1.66:5050 -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker version
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  tags:
    - deploy-shell
  only:
    - main
  script:
    - chmod +x deploy.sh
    - ./deploy.sh

post_deploy:
  stage: post_deploy
  tags:
    - deploy-shell
  only:
    - main
  script:
    - curl -f http://127.0.0.1:8080/health

changelog:
  stage: changelog
  image: alpine:3.20
  tags:
    - runner
  only:
    - main
  before_script:
    - apk add --no-cache bash git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.local"
    - chmod +x update_changelog.sh
  script:
    - ./update_changelog.sh
    - |
      if git diff --quiet CHANGELOG.md; then
        echo "CHANGELOG.md не изменился"
        exit 0
      fi
    - git add CHANGELOG.md
    - 'git commit -m "ci: update changelog [skip ci]"'
    - 'git remote set-url origin "http://oauth2:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"'
    - 'git push origin HEAD:${CI_COMMIT_BRANCH}'

wiki_update:
  stage: wiki_update
  image: alpine:3.20
  tags:
    - runner
  only:
    - main
  before_script:
    - apk add --no-cache curl
  script:
    - |
      WIKI_CONTENT="# FastAPI Todo DevOps

      ## О проекте
      ВКР DevOps-проект: FastAPI + Docker + GitLab CI/CD + Docker Compose.

      ## Что уже реализовано
      - test
      - build
      - deploy
      - post_deploy
      - автоматическая публикация CHANGELOG

      ## Проверка приложения
      Health endpoint:
      - /health
      "
      STATUS_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
        --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/wikis/home")

      if [ "$STATUS_CODE" = "200" ]; then
        curl --request PUT \
          --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
          --data-urlencode "title=Home" \
          --data-urlencode "content=${WIKI_CONTENT}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/wikis/home"
      else
        curl --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
          --data-urlencode "title=Home" \
          --data-urlencode "content=${WIKI_CONTENT}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/wikis"
      fi