services:
  app:
    image: ${IMAGE_NAME:-192.168.1.66:5050/monarch/fastapi-todo-devops:latest}
    restart: unless-stopped
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      APP_COMMIT_SHA: ${APP_COMMIT_SHA:-local}
      APP_RELEASE: ${APP_RELEASE:-dev}

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro